spring.datasource.url=jdbc:postgresql://tradelearn_dbb_user:REDACTED_DB_PASSWORD_2@dpg-d5ools49c44c73fc4iug-a.oregon-postgres.render.com/tradelearn_dbb
spring.datasource.username=tratradelearn_dbb_user

spring.datasource.password=REDACTED_DB_PASSWORD_2


spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
